name: "covdata-percent"
description: Report go covdata percentages in Pull Requests
inputs:
  repo_token:
    description: "The GITHUB_TOKEN for this repo"
    required: true
    default: ${{ github.token }}
  path:
    description: "Path to the coverage report."
    required: true
    default: "coverage/percent"
  skip_covered:
    description: "If files with 100% should be skipped from report."
    required: true
    default: true
  minimum_coverage:
    description: "Minimum allowed coverage percentage as an integer."
    required: true
  fail_below_threshold:
    description: "Fail the action when the minimum coverage was not met."
    required: false
    default: false
  only_changed_files:
    description: "Only show coverage for changed files. (only if a PR is present)"
    required: true
    default: false
  pull_request_number:
    description: "Pull request number associated with the report. This property should be used when workflow trigger is different than pull_request."
    required: false
    default: ""
  report_name:
    description: "Use a unique name for the report and comment."
    required: false
    default: ""
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "percent"
  color: "green"
